"""Run real validation commands and record gate evidence; no PASS is generated by templates."""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from src.common.artifacts import file_hash,fingerprint,write_json
from src.common.config import load_config


def main() -> int:
    parser=argparse.ArgumentParser();parser.add_argument('--step',required=True);parser.add_argument('--role',required=True,choices=['A','B','C'])
    parser.add_argument('--command',action='append',required=True);parser.add_argument('--artifact',action='append',default=[])
    parser.add_argument('--acceptance',choices=['UNMEASURED','FAIL','PASS'],default='UNMEASURED')
    parser.add_argument('--summary',help='Codex-generated Korean one-line summary of actual changes; used for the automatic commit')
    parser.add_argument('--metrics',type=Path);args=parser.parse_args();cfg=load_config()
    if args.summary is not None and ('\n' in args.summary or '\r' in args.summary or not re.search('[가-힣]',args.summary)):
        raise ValueError('summary must be one Korean line')
    commands=[];logs=Path('.team/checks')/args.step;logs.mkdir(parents=True,exist_ok=True)
    for i,command in enumerate(args.command):
        with (logs/f'{i}.log').open('w') as output:
            result=subprocess.run(['bash','-lc',command],stdout=output,stderr=subprocess.STDOUT)
        commands.append({'command':command,'exit_code':result.returncode})
        print(f'{args.step}: exit {result.returncode}: {command}')
    manifest=json.loads(Path(cfg['paths']['data_dir'],'split_manifest.json').read_text())
    accepted=args.acceptance
    if accepted=='PASS':
        if cfg['scale']!='full' or not args.metrics:raise ValueError('full scale and measured metric JSON required for acceptance PASS')
        measured=json.loads(args.metrics.read_text())
        from src.evaluation.acceptance import validate_acceptance
        validate_acceptance(measured,cfg,manifest,Path.cwd())
        if not all(c['exit_code']==0 for c in commands):
            raise ValueError('failed validation cannot establish acceptance PASS')
    for name in args.artifact:
        if not Path(name).exists():raise ValueError(f'missing declared artifact: {name}')
    value={'step':args.step,'owner':args.role,'status':'PASS' if all(c['exit_code']==0 for c in commands) else 'FAIL',
           'scale':cfg['scale'],'acceptance':accepted,'commands':commands,'artifacts':args.artifact,
           'data_fingerprint':manifest['generation_fingerprint'],'config_fingerprint':fingerprint(cfg),
           'evaluation_version':'fixed-origin-v1','source_hashes':{name:file_hash(Path(name)) for name in args.artifact if Path(name).is_file()}}
    if args.summary:value['commit_summary_ko']=args.summary
    write_json(Path(f'docs/results/gates/{args.step}.json'),value)
    return 0 if value['status']=='PASS' else 1


if __name__=='__main__':raise SystemExit(main())
